import FormPizza from "@/components/Form/FormPizza";
import FirebaseService from "@/lib/firebase.services";
import { PencilSquareIcon, TrashIcon } from "@heroicons/react/24/solid";
import SearchIcon from "@rsuite/icons/Search";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { ClipLoader } from "react-spinners";
import {
  Breadcrumb,
  Button,
  Input,
  InputGroup,
  Pagination,
  Panel,
  Stack,
  Table,
} from "rsuite";

const { Column, HeaderCell, Cell } = Table;

export default function Pizzas() {
  const [open, setOpen] = useState(false);
  const [temp, setTemp] = useState([]);
  const [filterText, setFilterText] = useState("");

  const { user } = FirebaseService.useAuthState();
  const { data, loading, error } = FirebaseService.getDocument(
    "pizzas",
    "name",
    "asc"
  );

  const createHandler = () => {
    setOpen(true);
    setTemp([]);
  };

  const updateHandler = (item: any) => {
    setOpen(true);
    setTemp(item);
  };

  const deleteData = async (id: string, name: string) => {
    var result = confirm(`Deseja excluir: ${name}?`);
    if (result) await FirebaseService.deleteDocument("pizzas", id);
  };

  const toggleStatus = async (prod: any) => {
    await FirebaseService.updateDocument("pizzas", prod.id, {
      status: !prod.status,
    });
  };

  const filteredItems = data?.filter(
    (item: any) =>
      item.name && item.name.toLowerCase().includes(filterText.toLowerCase())
  );

  return (
    <>
      <Head>
        <title>Pizza</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="container p-6 mx-auto">
        {error && <strong>Error: {JSON.stringify(error)}</strong>}
        {loading && <ClipLoader color="#36d7b7" />}
        {data && (
          <Panel
            bordered
            header={
              <>
                <h3 className="title">Pizza</h3>
                <Breadcrumb>
                  <Breadcrumb.Item href="/">Home</Breadcrumb.Item>
                  <Breadcrumb.Item active>Pizza</Breadcrumb.Item>
                </Breadcrumb>
              </>
            }
            className="bg-white"
          >
            <Stack
              className="table-toolbar pb-3"
              justifyContent="space-between"
            >
              <Stack spacing={6}>
                <Button
                  color="blue"
                  appearance="primary"
                  // disabled={!user}
                  onClick={() => createHandler()}
                >
                  Cadastrar Pizza
                </Button>
                <Link href="/menu/additionals">
                  <Button color="blue" appearance="primary">
                    + Borda Recheada
                  </Button>
                </Link>
                <Link href="/menu/optionals">
                  <Button color="blue" appearance="primary">
                    + Adicionais
                  </Button>
                </Link>
              </Stack>

              <Stack spacing={6}>
                <InputGroup inside>
                  <Input
                    placeholder="Pesquisar"
                    value={filterText}
                    onChange={setFilterText}
                  />
                  <InputGroup.Addon>
                    <SearchIcon />
                  </InputGroup.Addon>
                </InputGroup>
              </Stack>
            </Stack>
            <Table bordered virtualized height={400} data={filteredItems}>
              <Column width={50} align="center" fixed>
                <HeaderCell>#</HeaderCell>
                <Cell dataKey="id">{(rowData, index: any) => ++index}</Cell>
              </Column>

              <Column flexGrow={1}>
                <HeaderCell>Nome</HeaderCell>
                <Cell>{(rowData) => rowData.name}</Cell>
              </Column>

              <Column flexGrow={1}>
                <HeaderCell>Preço Broto</HeaderCell>
                <Cell>
                  {(rowData) =>
                    rowData.priceOne.toLocaleString("pt-br", {
                      style: "currency",
                      currency: "BRL",
                      minimumFractionDigits: 2,
                      maximumFractionDigits: 2,
                    })
                  }
                </Cell>
              </Column>

              <Column flexGrow={1}>
                <HeaderCell>Preço Grande</HeaderCell>
                <Cell>
                  {(rowData) =>
                    rowData.priceTwo.toLocaleString("pt-br", {
                      style: "currency",
                      currency: "BRL",
                      minimumFractionDigits: 2,
                      maximumFractionDigits: 2,
                    })
                  }
                </Cell>
              </Column>

              {/*<Column flexGrow={1}>
                <HeaderCell>Ativo</HeaderCell>
                <Cell>
                  {(rowData) => (
                    <Toggle
                      disabled={!user}
                      checked={rowData.status}
                      onChange={() => toggleStatus(rowData)}
                    />
                  )}
                </Cell>
              </Column>*/}

              <Column flexGrow={1}>
                <HeaderCell>Ação</HeaderCell>
                <Cell>
                  {(rowData) => (
                    <div className="flex gap-4">
                      <button
                        //disabled={!user}
                        onClick={() => updateHandler(rowData)}
                        className="text-green-500 hover:text-green-800 disabled:text-gray-300"
                      >
                        <PencilSquareIcon className="w-4 h-4" />
                      </button>
                      <button
                        //disabled={!user}
                        onClick={() => deleteData(rowData.id, rowData.name)}
                        className="text-red-500 hover:text-red-800 disabled:text-gray-300"
                      >
                        <TrashIcon className="w-4 h-4" />
                      </button>
                    </div>
                  )}
                </Cell>
              </Column>
            </Table>
            <div className="p-4">
              <Pagination layout={["total"]} total={filteredItems.length} />
            </div>
          </Panel>
        )}
        {open && (
          <FormPizza open={open} onClose={() => setOpen(false)} temp={temp} />
        )}
      </section>
    </>
  );
}
